name: Build Release

on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

jobs:
  build:

    runs-on: windows-latest

    steps:
      - name: Checkout
        uses: actions/checkout@v2.3.4
      - name: setup-msbuild
        uses: microsoft/setup-msbuild@v1.0.2
      - name: msbuild
        run: msbuild /property:Configuration=Release
      - name: debug_dirlist
        run: gci -recurse
      - name: Create Release
        id: create_release
        uses: "marvinpinto/action-automatic-releases@latest"
        with:
          repo_token: "${{ secrets.GITHUB_TOKEN }}"
          automatic_release_tag: "latest"
          title: Release ${{ github.ref }}
          files: release\bin\netview.exe
          prerelease: false

