name: C/C++ CI

on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

jobs:
  build:

    runs-on: windows-latest

    steps:
    - uses: actions/checkout@v2
    - name: make
      run: make
    - name: Create Release
      id: create_release
      uses: "marvinpinto/action-automatic-releases@latest"
      env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
      with:
        automatic_release_tag: "latest"
        release_name: Release ${{ github.ref }}
        body: |
          Changes in this Release
          - Auto building
        files: netview.exe

